### ISSUE TITLE
findJavaGadget不返回结果

### ISSUE THREAD

**Issue by Le1a** [wh1t3p1g/tabby-path-finder#2]
# 2022长城杯-b4bycoffee

按照春秋伽玛的文章，安装了插件，也分析了所有jdk依赖 和题目相关依赖的jar包，但是跑不出来文章中的结果。
```
match (source:Method {NAME:"readObject",CLASSNAME:"java.util.HashMap"})
match (sink:Method {NAME:"toString"})
with source, collect(sink) as sinks
call tabby.algo.findJavaGadget(source, sinks, 12, false) yield path where none(n in nodes(path) where n.CLASSNAME in ["javax.management.BadAttributeValueExpException","com.sun.jmx.snmp.SnmpEngineId","com.sun.xml.internal.ws.api.BindingID","javax.swing.text.html.HTML$UnknownTag"])
return path limit 1
```
![image](https://user-images.githubusercontent.com/97610822/204216654-9f4f16f9-4764-44c3-94af-135a973ed6d9.png)
![image](https://user-images.githubusercontent.com/97610822/204216670-cfede888-42bc-40a2-9fe2-9635774601bd.png)

**Comment by wh1t3p1g** [comment]
检查一下是否开启了污点分析，插件需要带污点的代码属性图

**Comment by Le1a** [comment]
怎么开污点分析哇 是这个吗？
![image](https://user-images.githubusercontent.com/97610822/204219782-0726e684-28a5-467c-b590-9c5329bc8643.png)

**Comment by wh1t3p1g** [comment]
对的 改成false

**Comment by Le1a** [comment]
好滴 谢谢师傅！

**Comment by wh1t3p1g** [comment]
不客气哈  tabby 1.0 应用插件的效果没有实际做过测试，结果只能仅供参考。
不过之前那篇文章应该用的 1.0 的版本，可以实际尝试看看
