### ISSUE TITLE
neo4j v5.3.0 无法使用

### ISSUE THREAD

**Issue by veo** [wh1t3p1g/tabby-path-finder#3]
尝试了好多次运行`call tabby.help("tabby")`，都显示

Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `tabby.help`: Caused by: org.neo4j.internal.kernel.api.exceptions.ProcedureException: There is no procedure with the name `dbms.procedures` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

**Comment by wh1t3p1g** [comment]
最新版已适配 neo4j v5.x
